// This file was generated by Mendix Modeler 7.9.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package disabledefaultlogin.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the DisableDefaultLogin module

	public static java.lang.String getAdminUserName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DisableDefaultLogin.AdminUserName");
	}

	public static boolean getEnabled()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("DisableDefaultLogin.Enabled");
	}

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DisableDefaultLogin.LogNode");
	}
}