// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package disabledefaultlogin.actions;

import com.mendix.core.Core;
import com.mendix.core.action.user.LoginAction;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import disabledefaultlogin.helpers.HandleLoginAction;
import disabledefaultlogin.helpers.LoginActionListener;

public class OverwriteDefaultLoginAction extends CustomJavaAction<java.lang.Boolean>
{
	public OverwriteDefaultLoginAction(IContext context)
	{
		super(context);
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		LoginActionListener loginActionListener = new LoginActionListener(LoginAction.class);
		loginActionListener.addReplaceEvent(HandleLoginAction.class.getName());
		Core.addUserAction(HandleLoginAction.class);
		Core.getListenersRegistry().addListener(loginActionListener);
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "OverwriteDefaultLoginAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
